### PR TITLE
Initial 1.11.2 port

### PR DESCRIPTION
**Pull request by Mohron**
I thought it would be nice to see your mod back in 1.11.2, so I ported it for you.
Should solve #51

### CODE REVIEW

**Comment by Mohron** [comment]
Since Mantle is back, I can look into adding it back as a dependency.

**Comment by Mohron** [comment]
@RenEvo Do you plan on merging/updating NetherCore? I know your license is very permissive but I have no interest in taking credit for your work. I would much rather see an update published under your name and CurseForge project.

**Comment by renevo** [comment]
Totally missed this PR, will check it out today.

**Comment by renevo** [comment]
Looks good on the surface, like the removal of Mantle as well, that one was in/out in the beginning of the mod, definately didn't want a hard dependency on it.

Will pull it down either today/tomorrow and do my testing on it then see if I can get it shipped out.

Again, thanks for the effort on this, been a bit busy with a side project at home, and hadn't had time to get this updated just yet!

**Pull request merged**
